/** Map listing_type → category slug for auto category_id on create */
export const LISTING_TYPE_CATEGORY_SLUG = {
  subscription: 'subscriptions',
  donate: 'topups',
  topup: 'topups',
  keys: 'gift-cards',
  skins: 'items',
  games: 'other',
  account: 'accounts',
  game_account: 'accounts',
  clean_account: 'accounts',
  item: 'items',
  currency: 'game-currency',
  boosting: 'boosting',
  services: 'other',
  media: 'social',
  rental: 'other',
  region_change: 'other',
  mods: 'other',
  design: 'other',
  training: 'other',
  license: 'gift-cards',
  software: 'gift-cards',
  other: 'other',
  giftcard: 'gift-cards',
  steam_rewards: 'other',
  stars: 'topups',
  premium: 'subscriptions',
  nft_gifts: 'other',
  channels: 'social',
  usernames: 'social',
  advertising: 'social',
  bots: 'other',
  groups: 'social',
  stickers: 'other',
  clickers: 'other',
  coins: 'topups',
  promotion: 'social',
  montage: 'social',
  ps_plus: 'subscriptions',
  ea_play: 'subscriptions',
  youtube_music: 'subscriptions',
  youtube_tv: 'subscriptions',
  game_pass: 'subscriptions',
  ubisoft_plus: 'subscriptions',
  voices: 'topups',
  vk_music: 'subscriptions',
  vk_play: 'other',
  gifts: 'other',
  twitch_drops: 'other',
  bits: 'topups',
  tariff: 'subscriptions',
  tokens: 'topups',
  diamonds: 'topups',
  superlikes: 'topups',
  beans: 'topups',
  promocodes: 'gift-cards',
  plugins: 'other',
  guides: 'other',
  zems: 'topups',
  packs: 'items',
  product_design: 'other',
  images: 'other',
  design_packs: 'items',
  mochi: 'topups',
  servers: 'social',
};

export function categoryIdForListingType(listingType, categories = []) {
  const slug = LISTING_TYPE_CATEGORY_SLUG[listingType];
  if (!slug || !categories?.length) return '';
  const found = categories.find((c) => c.slug === slug);
  return found?.id ? String(found.id) : '';
}
