/** URL path segment ↔ listing_type for assortment landings */
export const OFFER_PATH_BY_TYPE = {
  subscription: 'subscriptions',
  donate: 'donate',
  account: 'accounts',
  item: 'items',
  topup: 'topup',
  keys: 'keys',
  other: 'other',
  currency: 'currency',
  game_account: 'game-accounts',
  clean_account: 'clean-accounts',
  boosting: 'boosting',
  services: 'services',
  skins: 'skins',
  games: 'games',
  media: 'media',
  rental: 'rental',
  region_change: 'region-change',
  mods: 'mods',
  design: 'design',
  training: 'training',
  license: 'license',
  software: 'software',
  giftcard: 'gift-cards',
  steam_rewards: 'steam-rewards',
  stars: 'stars',
  premium: 'premium',
  nft_gifts: 'nft-gifts',
  channels: 'channels',
  usernames: 'usernames',
  advertising: 'advertising',
  bots: 'bots',
  groups: 'groups',
  stickers: 'stickers',
  clickers: 'clickers',
  coins: 'coins',
  promotion: 'promotion',
  montage: 'montage',
  ps_plus: 'ps-plus',
  ea_play: 'ea-play',
  youtube_music: 'youtube-music',
  youtube_tv: 'youtube-tv',
  game_pass: 'game-pass',
  ubisoft_plus: 'ubisoft-plus',
  voices: 'voices',
  vk_music: 'vk-music',
  vk_play: 'vk-play',
  gifts: 'gifts',
  twitch_drops: 'twitch-drops',
  bits: 'bits',
  tariff: 'tariff',
  tokens: 'tokens',
  diamonds: 'diamonds',
  superlikes: 'superlikes',
  beans: 'beans',
  promocodes: 'promocodes',
  plugins: 'plugins',
  guides: 'guides',
  zems: 'zems',
  packs: 'packs',
  product_design: 'product-design',
  images: 'images',
  design_packs: 'design-packs',
  mochi: 'mochi',
  servers: 'servers',
  gold: 'gold',
  sounds: 'sounds',
  elixir: 'elixir',
  trovo_ace: 'trovo-ace',
  mana: 'mana',
  addons: 'addons',
  nitro: 'nitro',
  decorations: 'decorations',
  nintendo_switch_online: 'nintendo-switch-online',
  bonds: 'bonds',
};

export const TYPE_BY_OFFER_PATH = Object.fromEntries(
  Object.entries(OFFER_PATH_BY_TYPE).map(([type, path]) => [path, type])
);

export function offerPathForType(listingType) {
  if (!listingType) return null;
  return OFFER_PATH_BY_TYPE[listingType] || null;
}

export function listingTypeFromOfferPath(pathSegment) {
  if (!pathSegment) return null;
  return TYPE_BY_OFFER_PATH[String(pathSegment).toLowerCase()] || null;
}
